### ISSUE TITLE
Documentation: How to disable unused channels

### ISSUE THREAD

**Issue by heinemannj** [nliaudat/floor-heating-controller#7]
I have only 6 heating circuits of the available 8 channels in use.

How to disable/deactivate channel 7 and 8 to avoid the creation/usage of the not required sensors within the ESP and/or HA?

**Comment by heinemannj** [comment]
> You can comment out all the CH7-8 related parts in the code or delete the hassio sensors

Meaning in all of the following files of [floor-heating-controller](https://github.com/nliaudat/floor-heating-controller/tree/main)?

- climate.yaml
- config.yaml
- covers.yaml
- inputs.yaml
- script_calibrate_valves.yaml
- script_termostat_check.yaml
- sensor_adc.yaml
- sensor_bemf.yaml
- switch_gpio.yaml
- switch_others.yaml
- time.yaml

**Comment by nliaudat** [comment]
fixe in v105 release. 

Every channel is configured in config and pushed by packages as template

**Comment by derpeter** [comment]
I hope its ok to open this issue again.  I just got my PCBs and start to work on the firmware and casing.

It seems with the current firmware this is not trivial anymore.
I manged to disable channel 7 and 8 by not configuring it and uncommenting the relevant lines in scripte_calibrate_valves.
But if one needs an odd number of channel it gets tricky because of the linked channels for BEMF.

I toyed a little with the lambda functions but eventually it would seemed to me not worth the effort and im not (jet) deep enough in the firmware to understand all side effects.

So did i missed the easy way to configure this or is it just not implemented in the current version.
